import Head from 'next/head'
import styles from '../../styles/Home.module.css'
import NavCard from "../components/NavCard";
import useSWR from 'swr'

const fetcher = (url:string) => fetch(url).then((res) => res.json())
export default function Home() {
    const { data } = useSWR('/api/hello', fetcher)

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.grid}>
          {
            [{
              url:'https://vercel.com',
              title:'Blog'
            },{
              url:'https://vercel.com',
              title:'PrivateService'
            }].map((item: any)=><NavCard key={item.url} record={item}/>)
          }
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span className={styles.logo}>
            OOCC.ES
          </span>
        </a>
      </footer>
    </div>
  )
}
