import Head from 'next/head'
import NavCard from "../components/NavCard";
import useSWR from 'swr'
import NAV_JSON from './nav.json'
const fetcher = (url:string) => fetch(url).then((res) => res.json())
export default function Home() {
    const { data } = useSWR('/api/hello', fetcher)

    return (
    <div>
      <Head>
        <title>Fleet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <main className='grid grid-cols-3 gap-4'>
          {
            NAV_JSON.map((item: any)=><NavCard key={item.url} record={item}/>)
          }
      </main>

      <footer >
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by
          <span>
            OOCC.ES
          </span>
        </a>
      </footer>
    </div>
  )
}
